services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bidmart_notifications
      POSTGRES_USER: bidmart
      POSTGRES_PASSWORD: bidmart
    ports:
      - "5432:5432"

  notification-service:
    container_name: bidmart-notification-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_NOTIFICATION_TOPIC: order.notification-requests
      KAFKA_CONSUMER_GROUP: notification-service
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
    ports:
      - "8086:8086"